#+TITLE: AWS Well-Architected
#+LANGUAGE: es
#+OPTIONS:
* Las preguntas iniciales

- ¿Cómo puedo saber si la arquitectura de mi infraestructura está bien hecha?
- ¿Cómo usamos el AWS Well-Arquitected Framework?

* AWS Well-Architetcted Framework

Ayuda a comprender las ventajas y desventajas de las decisiones que toma cuando crea sistemas en AWS. Mediante el uso del marco, aprenderá las prácticas recomendadas de arquitectura para diseñar y operar sistemas en la nube seguros, fiables, eficientes y rentables. [fn:1]

* Los pilares

| Nombre                    | Descripción                                                                                                                                                                                                                               |
|---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Excelencia Operativa      | La capacidad de soportar el desarrollo y ejecutar cargas de trabajo de manera eficaz, obtener información acerca de las operaciones y mejorar continuamente admitiendo procesos y procedimientos para ofrecer valor de negocio.           |
|---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Seguridad                 | Abarca la capacidad para proteger los datos, sistemas y activos.                                                                                                                                                                          |
|---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Fiabilidad                | La habilidad de que una carga de trabajo lleve a cabo la función prevista, de forma correcta y consistente en el momento esperado. Esto incluye la capacida de operar y probar la carga de trabajo a través de su ciclo de vida completo. |
|---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Eficiencia de rendimiento | La abilidad de utilizar recursos informáticos de manera eficiente para cumplir con los requisitos del sistema y mantener esa eficiencia a medida que la demanda cambia y la tecnología evoluciona.                                        |
|---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Optimización de costos    | La capacidad de ejecutar sistemas para entregar valor de negocio al menor precio                                                                                                                                                          |
|---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Sostenibilidad            | La habilidad de mejorar continuamente la sustentabilidad impacta en la reducción de energía incrementando la eficacia a través de todos los componentes de una carga de trabajo al maximizar los beneficios de los recursos proveídos y minimizando el total de los recursos requeridos. |

- *Carga de trabajo* (workload): Un conjunto de componentes que juntos entregan valor de negocio. 

El trabajo del arquitecto es sopesar entre estos pilares de acuerdo a las necesidades del negocio.


Distribuir habilidades en equipos en  lugar de tener un área centralizada con esa capacidad, hay reisgos cuando tomas esa decisión, por ejemplo, asegurarse que los equipos sigan estándares internos. Se mitigan estos riesgos teniendo /prácticas/  (formas de hacer cosas, procesos, estándares y normas aceptadas ) y /mecanismos/ que permiten la revisión automática de asegurar que se cumplan los estándares. 

** Principios generales de diseño

- Deja de adivinar los recursos que necesitas.
- Prueba los sistemas a escala productiva.
- Automatiza para hacer la experimentación arquitectónica fácil.
- Permite  evolucionar las arquitecturas.
- Dirige tu aquitectura basada en datos.
- Realiza mejoras a través de días de prueba (game days). 

* Excelencia operativa
** Principios  de diseño
- Realiza operaciones como código.
- Has cambios reversibles, pequeños y frecuentes.
- Redefine procedimientos operacionales frecuentemente. Organiza /game days/ regulares para revisar y validar que todo los porocedimiento son efectivos y que los miembros del equipo están familiarizados con ellos.
- Anticipa el fracaso. Prueba tus escenario sde falla y valida su entendimiento y su impacto.
- Aprende de todas las fallas operacionales. 
** Áreas de mejores prácticas

- Organización
  El equipo dete tener un conocimiento compartido de las metas del negocio.
  Prioridades bien definidas maximizan el beneficio de tus esfuerzos.
  Evalua los las amenazas y evalúa el impacto de los riesgos.
  El equipo debe tener claro su rol y su impacto en las metas del negocio.
  Respalda a los miembros del equipo de tal forma que tomen acciones y apoyen los beneficios de tu negocio.
  Fomenta la experimentación para acelerar el aprendizaje y mantener a los miembros del equipo involucrados.
  Mantente al tanto de las regulaciones externas que aplican a tu organización. 

- Preparación
  Tienes que entender tus cargas de trabajo y su comportamiento esperado.
  Diseña tu carga de trabajo que provea la información necesaria para conocer su estado.
  Adopta prácticas que mejoren el flujo de cambios a producción y que habiliten la refactorización, retroalimentación rápida sobre la calidad y resolución de bugs.
  
- Operación
  Una operación exitosa es medida por el logro de las metas de negocio y del cliente. Define los resultados esperados y determina cómo será medido este éxito.
  Una operación saludable incluye cargas de trabajo saludables y actividades de operacion saludables (deployment y respuesta a incidencias).
  Un manejo efectivo y eficiente es necesario para alcanzar la excelencia operativa. (Priorizar, establecer runbooks, estabelce alertas).
  Comunica el estatus operacional de tus cargas de trabajo mediante dashboards
  
- Evolución
  Debes aprender, compartir y mejorar continuamente mejorar para mantener tu excelencia operativa. Cambios continuos y mejoras incrementales. Post-incident análisis de todos los eventos que impactan al cliente.
  Incluye sesiones de feedback en tus procedimientos para identificar rápidamente áreas de mejora y obneter.
  
  
* Seguridad

** Principios de diseño
- Implementa una fuerte base de identidad. Identifica el principio de /least privilege/ y fomenta la separación de funciones con la autorización apropiadapara cada interacción con los recursos de AWS.
- Habilita la trazabilidad: Monitorea, alerta y audita acciones y cambios en tus ambientes en tiempo real.
- Aplica seguridad a todos los niveles. VPC, loadbalancing, cada instancia y sistema operativo.
- Automatiza las mejores prácticas de seguridad.
- Protege los datos en tránsito y el resto. DSP
- Prepárate para incidentes de seguridad.

** Mejores prácticas
- Seguridad
  Aplica todas las mejores prácticas de seguridad en cada ará de seguridad.
- Identity y Access Management
  Asegúrate qyue solo usuarios autenticados y autorizados sean capaces de acceder a tus recursos y sólo de la manera que se determine.
- Detection.
  Utiliza controles de detección para identificar amenazas de seguridad o incidentes. (Inventario de assets, internal auditing, procesamiento d elogs)
- Protección de Infraestructura
  Abarca metodologías de control, como la defenza en profundidad, necesarias para cumplir con las mejores prácticas y las obligaciones organizativas. 
- Data Protection 
  *Antes de diseñar una arquitectura* -> data classification
    
- Respuesta a incidentes
  Aún con controles preventivos y de detección tu organización debe establecer procesos para responder y mitigar potenciales impactos a incidentes de seguridad. 

* Confiabilidad
** Principios de diseño
- Recupérate automáticamente de las fallas.
- Pureba procedimientos de recupearación.
- Escala horizontalmente para incrementar la disponibilida de las cargas de trabajo
- Deja de adivinar la capacidad que requieres.
- Gestiona el cambio con la automatización.

** Mejores prácticas
- Foundations.
  Requerimientos de inicio que debe cumplir tu arquitectura. 
- Arquitectura de las cargas de trabajo.
  Una carga de trabajo confiable comienza con decisiones de diseño iniciales tanto para software como para infraestructura. (SOA, Microservices)
- Change management.
  Cambios en tu carga de trabajo o en su ambiente deben ser anticipados y acomodarse para alcanzar una operación confiable en la carga de trabajo. (Spikes in demand, feature deployments, security patches)
- Gestión de las fallas. 
  Tu carga de trabajo esté consciente de las fallas tan proto como estas ocurran y tomar acciones para evitar un impacto en la disponibilidad.
  
* Eficiencia en redimiento
** Principios de diseño
- Democratica tecnologías avanzadas.
- Lanza globalmente en minutos
- Usa arquitecturas serverless
- Experimenta seguido
- Busca simpatía mecánica. Siempre usa la solución tecnológica que mejor se ajuste con los objetivos de tu carga de trabajo.

** Mejores prácticas
- Selección.
  La solución óptima para una carga de trabajo varía, y las soluciones regularmente combina diferentes aproximaciones.
  - Cómputo. Instancias, Contenedores o Funciones.
  - Storage. Object Storage, Block Storeage, File Storage. 
  - Database. 
  - Network. Bandwithd
- Revisión.
  Evalúa de forma contínua que los componentes de tu carga de trabajo estén utilizando las últimas tecnologías y se aproxime a mejorar continuamente el rendimiento.
- Monitoreo.
  Debes monitorear el performace de tus cargas de trabajo para poder remediar cualquier eventualidad antes de que impacte a tus clientes. 
- Tradeoff.
  Ej. consistencia o durabilidad, tiempo o espacio. 

* Optimización de costos

** Principios de diseño
- Implementa el manejo financiero de la nube.
- Adopta un modelo de consumo. Paga sólo por los recursos computacionales que usas.
- Mide la eficacia
- No gastes dinero en tareas pesadas (heavy lifting)
- Analiza y atribuye gastos
  
** Mejores prácticas
- Practica el manejo financiero de la nube. 
- Concientiza el gasto y el uso.
  La capacidad de attibuir costos por recursos para la organización o para los product owners conduce a un comportamiento de uso eficiente  y reducción de desperdicios.
- Recursos Costo/Eficacia
- Gestiona la demanda y provisionamiento de recursos.
- Optimiza conforme pase el tiempo.

* Sustentabilidad

** Principios de diseño
- Comprende tu impacto
- Establece tus metas de sostenibilidad
- Maximiza tu utilización de recursos
- Anticipa y adopta nuevo las ofertas de software más eficientes
- Usa servicios manejados. - Cloud
- Reduce el impacto posterior de sus cargas de tabajo en la nube.

** Mejores prácticas
- Selección de región. 
- Behavior patterns. 
- Patrones de software y arquitectura.
- Patrones de datos.
  Energy efficient hardware, SSD.
  Elimina datos redundantes.
  Usa sistemas de archivos compartidos
  Respalda información cuando sea difícil de recrear
- Patrones de Hardware.
  Utiliza el hardware mínimo para atender tus necesidades.
  Utiliza instancias con el menor impacto
  Opotimiza el uso de GPUS
- Patrones de desarrollo y deployment
  Adopta métodos que introduzcan sutentablemente mejoras.
  Manten tus cargas de trabajo actualizadas.
  Incrementa la utilización de ambientes de construcción. Programa los periodos de disponibilidad para que coincidan con los horarios de trabajo de los miembros de trabajo.
  


* Footnotes

[fn:1] [[https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html][AWS Well-Architected Framework]] - https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html
